GesRelationClient/Controllers/AppelController.cs
using GesRelationClient.Models;
using GesRelationClient.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GesRelationClient.Controllers
{
    [Authorize]
    public class AppelController : Controller
    {
        IRepositorie<Appel> _appelService;
        public AppelController(IRepositorie<Appel> appelService)
        {
            _appelService = appelService;
        }


        // GET: AppelController
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1, int pageSize = 10)
        {
            var apples = await _appelService.GetPaged(page, pageSize);
            var totalAppel = await _appelService.GetTotal();
            var totalPages = (int)Math.Ceiling((double)totalAppel / pageSize);

            var model = new AppelListPagedViewModel
            {
                apples = apples,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View(model);
        }


        // GET: AppelController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var appel = await _appelService.GetById(id);

            return View(appel);
        }
        // GET: AppelController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Appel appel)
        {
            if (ModelState.IsValid)
            {
                var result = await _appelService.Create(appel);
                if (result)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    ViewBag.ErrorMessage = "Echec";
                    return View(appel);
                }
            }

            ViewBag.ErrorMessage = "Veuillez remplir tous les champs.";
            return View(appel);
        }

        // GET: AppelController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var appel = await _appelService.GetById(id);

            return View(appel);
        }

        // POST: AppelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Appel appel)
        {
            if (ModelState.IsValid)
            {
                var result = await _appelService.Update(appel);
                if (result)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    ViewBag.ErrorMessage = "Echec";
                    return View(appel);
                }
            }

            ViewBag.ErrorMessage = "Veuillez remplir tous les champs.";
            return View(appel);
        }

        // GET: AppelController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var appel = await _appelService.GetById(id);

            return View(appel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteConfirme(int id)
        {

            var resu = await _appelService.Delete(id);

            return RedirectToAction(nameof(Index));

        }
    }
}

GesRelationClient/Controllers/ClientController.cs
using GesRelationClient.Models;
using GesRelationClient.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Drawing.Printing;

namespace GesRelationClient.Controllers
{
    [Authorize("ManagerOnly")]
    public class ClientController : Controller
    {
        IRepositorie<Client> _clientService;

        public ClientController(IRepositorie<Client> repositorie)
        {
            _clientService = repositorie;
        }
        // GET: ClientController
        [HttpGet]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10)
        {
            var clients = await _clientService.GetPaged(page, pageSize);
            var totalClients = await _clientService.GetTotal();
            var totalPages = (int)Math.Ceiling((double)totalClients / pageSize);

            var model = new ClientListPagedViewModel
            {
                Clients = clients,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View(model);
        }


        // GET: ClientController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var client = await _clientService.GetById(id);

            return View(client);
        }

        // GET: ClientController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (ModelState.IsValid)
            {
                var result = await _clientService.Create(client);
                if (result)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    ViewBag.ErrorMessage = "Echec";
                    return View(client);
                }
            }

            ViewBag.ErrorMessage = "Veuillez remplir tous les champs.";
            return View(client);

        }

        // GET: ClientController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var client = await _clientService.GetById(id);

            return View(client);
        }

        // POST: ClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Client client)
        {
            if (ModelState.IsValid)
            {
                var result = await _clientService.Update(client);
                if (result)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    ViewBag.ErrorMessage = "Echec";
                    return View(client);
                }
            }

            ViewBag.ErrorMessage = "Veuillez remplir tous les champs.";
            return View(client);
        }

        // GET: ClientController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var client = await _clientService.GetById(id);

            return View(client);
        }

        // POST: ClientController/Delete/5
        [HttpGet]
        public async Task<IActionResult> DeleteConfirme(int id)
        {

                var resu = await _clientService.Delete(id);

                return RedirectToAction(nameof(Index));

        }
    }
}

GesRelationClient/Views/Shared/_Layout.cshtml
@using System.Globalization;
@inject IViewLocalizer Localizer


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GesRelationClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GesRelationClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> @Localizer["Relation Client"] </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Acceuil"]</a>
                        </li>
                        @if ((await AuthorizationService.AuthorizeAsync(User, "EmployeOnly")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appel" asp-action="Index">@Localizer["Gérer les Appels"]</a>
                            </li>
                        }
                        @if ((await AuthorizationService.AuthorizeAsync(User, "ManagerOnly")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">@Localizer["Gérer les Clients"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rapport" asp-action="Index">@Localizer["Gérer le Rapport"]</a>
                            </li>
                        }

                    </ul>
                </div>
                
            </div>
            <partial name="_LoginSee" />
            @if (CultureInfo.CurrentCulture.Name.Equals("fr"))
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang="en">en</a>
            } else
            {
                CultureInfo.CurrentCulture = new CultureInfo("fr");
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang="fr">fr</a>
            }

        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="row">
            <div class="col-md-6">
                <p>&copy; @System.DateTime.Now.Year - GRC</p>
            </div>
            <div class="col-md-6 text-right">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GesRelationClient/Views/Shared/_LoginSee.cshtml
@using Microsoft.AspNetCore.Http;
@using System.Security.Claims;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Authentication.Cookies;
@inject IViewLocalizer Localizer

@{

    string? UserName = User.FindFirst("Nom")?.Value;
}

@if (User.Identity.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @UserName
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">

        <li>
            <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Logout"> @Localizer["Deconnexion"]</a>
        </li>
    </ul>

}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a class="btn btn-outline-success" asp-area="" asp-controller="Account" asp-action="Login"> @Localizer["Connexion"] </a>
        </li>
    </ul>

}

GesRelationClient/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" 
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
          onchange="this.form.submit();"
          asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>